#!/bin/bash

# vars
Icon=~/.local/share/nautilus/scripts/Aricon-files/ffmpeg.png
Notify_sound_complete=~/.local/share/nautilus/scripts/Aricon-files/notify.wav
Notify_sound_failed=~/.local/share/nautilus/scripts/Aricon-files/failed.ogg

# functions
not_complete () {
	rm $outname.$format
	notify-send -i "$Icon" "Not Completed, See LOG for more informations." &
	/usr/bin/canberra-gtk-play --volume 10 -f $Notify_sound_failed &
	exit 
}

completed () {
 	notify-send -i "$Icon" "Completed." &
	/usr/bin/canberra-gtk-play --volume 10 -f $Notify_sound_complete &
	rm ./LOG
}

# Codec names
MPEG2="mpeg2video"
X265="libx265"
X264="libx264"

# Zenity for codec
codec=$(zenity --title "Aricon" --window-icon "$Icon" --width 500 --height 250 --list --text "Choose your codec." --radiolist --column "Select" --column "Codecs" TRUE "$X265" FALSE "$X264" FALSE "$MPEG2" FALSE "copy" );

if [ "$?" = 1 ];
	then exit;
fi




# Output name and check if it's empty
while [ true ]; do
	outname=$(zenity --entry --window-icon "$Icon" --title="Aricon" --text="Please choose your output name." )
		if [ $? = 1 ];
			then exit;
		fi
	if [ "$outname" = "" ];
		then
			notify-send -i $Icon "You have to choose output name." &
			continue
		else
			break
	fi
done
		

if [ "$?" = 1 ];
	then exit;
fi

# Zenity for output format
format=$(zenity --title "Aricon" --window-icon "$Icon" --width 550 --height 300 --list --text "Choose your output format." --radiolist --column "Select" --column "Codecs" TRUE "mp4" FALSE "mkv" FALSE "mov" FALSE "avi" FALSE "wmv" );

if [ "$?" = 1 ];
	then exit;
fi

# chek that the file does not exist
if [[ -f ./"$outname"."$format" ]]; then
	zenity --error --title "Aricon" --text "The file already exists, change the output name." --window-icon "$Icon" --width 400 --height 100
	if [ "$?" = 1 ];
		then exit;
	fi
	exit
fi


# Start the Converting job
for video in "$1"
do
	ffmpeg -i "$video" -c:v "$codec" -c:a copy "$outname"."$format" 2>> ./LOG | zenity\
	--progress\
	--title="Aricon"\
	--text="Aricon is working, please wait..."\
	--window-icon "$Icon"\
	--no-cancel\
	--height=110\
	--width=360\
	--pulsate\
	--auto-close\
	--auto-kill\

	if [ "$?" = 0 ];
		then
			completed
	else
			not_complete
	fi
done 
 






